FROM arm64v8/php:7.4-fpm-alpine

ENV APP_DIR=/srv/app

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir /usr/bin --filename composer

# Install php extensions and basic libraries
RUN apk add --no-cache \
        freetype \
        libjpeg-turbo \
        libpng \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libzip-dev \
    && docker-php-ext-configure gd \
        --with-freetype=/usr/include/ \
        --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
        pdo \
        pdo_mysql \
        zip \
        bcmath \
    && docker-php-ext-enable gd \
    && apk del --no-cache \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
    && rm -rf /tmp/*

# Setup application
RUN mkdir -p ${APP_DIR}
COPY src/ ${APP_DIR}
WORKDIR ${APP_DIR}

# # add php.ini
# COPY docker/php/php.ini ${PHP_INI_DIR}/php.ini

# Change the access permission of specific forders for the needs of yii2 framework
RUN chmod -Rf 777 ${APP_DIR}/web/assets && \
    mkdir -p ${APP_DIR}/runtime && \
    chmod -Rf 777 ${APP_DIR}/runtime

# Expose 9000 port for internal comunication between containers
EXPOSE 9000
