# GitHub Action config for Testing Yii2 with MySQL
name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          # extensions: gd, zip, pdo, pdo_mysql

      - name: Run Docker Compose to deploy dev environment
        run: make build

      - name: Install Composer dependencies
        run: |
          cd src/
          composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Initiaize application
        run: |
          cd src/
          php tests/bin/yii migrate --interactive=0
        env:
          YII_DEBUG: true
          YII_ENV: test
          COOKIE_VALIDATION_KEY: test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DSN: mysql:host=mysqldb;dbname=main_db
          DB_DSN_TEST: mysql:host=mysqldb;dbname=test_db

      - name: Run Unit Tests
        run: |
          composer require --dev codeception/module-rest --no-cache --ignore-platform-reqs
          cd src/ && vendor/bin/codecept build
          cd ../ && docker-compose exec -T app vendor/bin/codecept run api
        env:
          YII_DEBUG: true
          YII_ENV: test
          COOKIE_VALIDATION_KEY: test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DSN: mysql:host=mysqldb;dbname=main_db
          DB_DSN_TEST: mysql:host=mysqldb;dbname=test_db

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test
