# GitHub Action config for Testing Yii2 with MySQL
name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, zip, pdo, pdo_mysql
          # coverage: xdebug

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Start mysql service
        run: sudo systemctl start mysql

      - name: Initiaize application
        run: |
          php yii migrate --interactive=0
        env:
          YII_DEBUG: true
          YII_ENV: test
          COOKIE_VALIDATION_KEY: test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DSN: mysql:host=127.0.0.1;dbname=main_db
          DB_DSN_TEST: mysql:host=127.0.0.1;dbname=test_db

      - name: Run Unit Tests
        run: |
          vendor/bin/codecept run api
        env:
          YII_DEBUG: true
          YII_ENV: test
          COOKIE_VALIDATION_KEY: test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DSN: mysql:host=127.0.0.1;dbname=main_db
          DB_DSN_TEST: mysql:host=127.0.0.1;dbname=test_db

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test
